FROM python:3.9-slim
WORKDIR /app
COPY app.py /app
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install Flask
EXPOSE 80
CMD ["python", "app.py"]